import { Product, CategoryInfo } from './types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'all', name: 'ทั้งหมด', name_en: 'All Meats', icon: '🥩' },
  { id: 'red_meat', name: 'เนื้อแดง', name_en: 'Red Meats', icon: '🥩' },
  { id: 'poultry', name: 'สัตว์ปีก', name_en: 'Poultry', icon: '🍗' },
  { id: 'seafood', name: 'อาหารทะเล', name_en: 'Seafood', icon: '🦐' },
  { id: 'premium_exotic', name: 'พรีเมียม & เอ็กโซติก', name_en: 'Premium & Exotic', icon: '👑' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p-01',
    code: 'NM-001',
    name: 'เนื้อหมูสันคอ',
    name_en: 'Pork Collar Cut',
    category: 'red_meat',
    price_per_kg: 180,
    stock_kg: 45.5,
    unit: 'kg',
    icon_emoji: '🐖',
    description: 'เนื้อหมูส่วนสันคอ แทรกไขมันนุ่ม ละมุน เหมาะสำหรับชาบู ย่าง และผัด',
    image_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-02',
    code: 'NM-002',
    name: 'เนื้อไก่อกนุ่ม',
    name_en: 'Tender Chicken Breast',
    category: 'poultry',
    price_per_kg: 120,
    stock_kg: 60.0,
    unit: 'kg',
    icon_emoji: '🐓',
    description: 'เนื้ออกไก่สด ไร้หนัง โปรตีนสูง เหมาะสำหรับสายสุขภาพและอาหารคลีน',
    image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
  {
    id: 'p-03',
    code: 'เนื้อปลาแซลมอนสด',
    name_en: 'Fresh Salmon Fillet',
    category: 'seafood',
    price_per_kg: 490,
    stock_kg: 25.0,
    unit: 'kg',
    icon_emoji: '🐟',
    description: 'เนื้อปลาแซลมอนเกรดพรีเมียม แล่สดวันต่อวัน หวานมัน มันแทรกกำลังดี',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-04',
    code: 'NM-004',
    name: 'เนื้อวัวริบอาย',
    name_en: 'Ribeye Beef Steak',
    category: 'red_meat',
    price_per_kg: 420,
    stock_kg: 30.0,
    unit: 'kg',
    icon_emoji: '🐂',
    description: 'เนื้อวัวส่วนริบอาย นุ่มฉ่ำ ลายไขมันสวย ชิ้นหนากำลังดีสำหรับสเต๊ก',
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-05',
    code: 'NM-005',
    name: 'เนื้อจระเข้ส่วนหาง',
    name_en: 'Crocodile Tail Meat',
    category: 'premium_exotic',
    price_per_kg: 450,
    stock_kg: 18.0,
    unit: 'kg',
    icon_emoji: '🐊',
    description: 'เนื้อจระเข้ส่วนบ้องหาง คอเลสเตอรอลต่ำ เนื้อแน่นนุ่มคล้ายเนื้อไก่ผสมปลา',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
  {
    id: 'p-06',
    code: 'NM-006',
    name: 'เนื้อแกะช็อปพรีเมียม',
    name_en: 'Premium Lamb Chop',
    category: 'red_meat',
    price_per_kg: 680,
    stock_kg: 15.5,
    unit: 'kg',
    icon_emoji: '🐑',
    description: 'ซี่โครงแกะนำเข้า เนื้อนุ่ม ไร้กลิ่นสาบ เหมาะสำหรับการย่างโรสแมรี่',
    image_url: 'https://images.unsplash.com/photo-1602881917760-7379db593981?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
  {
    id: 'p-07',
    code: 'NM-007',
    name: 'เนื้อวากิว A5',
    name_en: 'Japanese Wagyu A5 Steak',
    category: 'premium_exotic',
    price_per_kg: 2800,
    stock_kg: 10.0,
    unit: 'kg',
    icon_emoji: '🥩',
    description: 'เนื้อวากิวเกรด A5 ลายหินอ่อนละลายในปาก คุณภาพอันดับหนึ่งจากญี่ปุ่น',
    image_url: 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-08',
    code: 'NM-008',
    name: 'เนื้อโกเบพรีเมียม',
    name_en: 'Authentic Kobe Beef',
    category: 'premium_exotic',
    price_per_kg: 3500,
    stock_kg: 8.0,
    unit: 'kg',
    icon_emoji: '🥩',
    description: 'สุดยอดเนื้อโกเบแท้ นุ่มละมุน ละลายในลิ้น รสชาติเข้มข้นเป็นเอกลักษณ์',
    image_url: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-09',
    code: 'NM-009',
    name: 'เนื้อเป็ดอกเชอร์รี่',
    name_en: 'Cherry Duck Breast',
    category: 'poultry',
    price_per_kg: 190,
    stock_kg: 35.0,
    unit: 'kg',
    icon_emoji: '🦆',
    description: 'อกเป็ดเชอร์รี่สด หนังบาง เนื้อแน่น รสชาติเข้มข้น เหมาะสำหรับอบย่าง',
    image_url: 'https://images.unsplash.com/photo-1514944288352-fffac99f0bdf?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
  {
    id: 'p-10',
    code: 'NM-010',
    name: 'เนื้อกระต่ายอบเครื่องเทศ',
    name_en: 'Tender Rabbit Meat',
    category: 'premium_exotic',
    price_per_kg: 390,
    stock_kg: 12.0,
    unit: 'kg',
    icon_emoji: '🐇',
    description: 'เนื้อกระต่ายอนามัย ไขมันต่ำ โปรตีนสูง นิยมในเมนูสไตล์ฝรั่งเศสและอิตาเลียน',
    image_url: 'https://images.unsplash.com/photo-1579631542720-3a87824fff86?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
  {
    id: 'p-11',
    code: 'NM-011',
    name: 'เนื้อปูม้าก้อนแกะสด',
    name_en: 'Fresh Crab Jumbo Lump',
    category: 'seafood',
    price_per_kg: 850,
    stock_kg: 14.0,
    unit: 'kg',
    icon_emoji: '🦀',
    description: 'เนื้อปูม้าแกะสำเร็จรูป ก้อนใหญ่ สดหวาน รสชาติธรรมชาติโดยตรงจากทะเล',
    image_url: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-12',
    code: 'NM-012',
    name: 'เนื้อกุ้งลายเสือสด',
    name_en: 'Tiger Prawn Meat',
    category: 'seafood',
    price_per_kg: 380,
    stock_kg: 28.0,
    unit: 'kg',
    icon_emoji: '🦐',
    description: 'เนื้อกุ้งลายเสือไซส์ใหญ่ เด้ง กรอบ หวาน สด สะอาด พร้อมปรุงทันที',
    image_url: 'https://images.unsplash.com/photo-1559737113-5a15775ae7be?auto=format&fit=crop&w=800&q=80',
    is_popular: true,
  },
  {
    id: 'p-13',
    code: 'NM-013',
    name: 'เนื้อปลาหมึกหอมสด',
    name_en: 'Fresh Cut Squid',
    category: 'seafood',
    price_per_kg: 290,
    stock_kg: 32.0,
    unit: 'kg',
    icon_emoji: '🦑',
    description: 'ปลาหมึกหอมเนื้อหนา นุ่มเด้ง หั่นชิ้นสวยงาม เหมาะสำหรับปิ้งย่างและผัด',
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    is_popular: false,
  },
];
